export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",


    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    LOGGEDIN : "LOGGEDIN",
    LOGIN_ERROR : "LOGIN_ERROR",





    
    
}