export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",


    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAIL:"REGISTER_FAIL",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAIL:"LOGIN_FAIL",
    LOGOUT:"LOGOUT" , 
    SET_MESSAGE:"SET_MESSAGE",
    CLEAR_MESSAGE:"CLEAR_MESSAGE",

    
}