export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",

    //For user


    LOGIN: "LOGIN",
    ADD_USER: "ADD_USER",
    UPDATE_USER:"UPDATE_USER",
    UPDATE_PROFILE_PICTURE:"UPDATE_PROFILE_PICTURE",
    FORM_SUBMISSION_STATUS:"FORM_SUBMISSION_STATUS",


}